### Create a new user
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test3@example.com",
  "password": "password123"
}

### Signin
POST  http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "test3@example.com",
  "password": "password123"
}

### Get the currently signed in user
GET http://localhost:3000/auth/whoami

### Find a particular user with a given id
GET http://localhost:3000/auth/1

### Find all users by email
GET http://localhost:3000/auth?email=test@example.com

### Delete a user with a given id
DELETE http://localhost:3000/auth/2

### Update a user with a given id
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "asdl@testinc.com",
  "password": "new1password"
}

