POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Toyota",
    "model": "Corolla",
    "year": 2020,
    "price": 20000,
    "mileage": 15000,
    "lng": 0,
    "lat": 0
}

### Approve a report
PATCH http://localhost:3000/reports/7
Content-Type: application/json

{
    "approved": true
}


### Get an estimate
GET http://localhost:3000/reports?make=Toyota&model=Corolla&year=2020&lng=0&lat=0&mileage=15000